apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-app-example
  namespace: default
spec:
  type: Python
  mode: cluster
  image: arthrok/spark:latest
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///opt/spark/src/myjob.py"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: 512m
    labels:
      version: 3.5.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: 512m