apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-app-examples
  namespace: spark-operator
spec:
  type: Python
  mode: cluster
  image: arthrok/spark:latest
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/src/second-job.py"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: 512m
    labels:
      version: 3.5.0
    serviceAccount: spark-operator-spark
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: spark-driver
              operator: In
              values:
              - "true"

  executor:
    cores: 1
    instances: 1
    memory: 512m
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: spark-executor
              operator: In
              values:
              - "true"

  dynamicAllocation:
    enabled: true
    initialExecutors: 1
    minExecutors: 1
    maxExecutors: 3